OnlineEdu.WebUI/Areas/Teacher/Controllers/MySocialMediaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.TeacherSocialDtos;
using OnlineEdu.WebUI.Services.TokenServices;

namespace OnlineEdu.WebUI.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    [Authorize(Roles = "Teacher")]
    
        public class MySocialMediaController: Controller
        {
        private readonly HttpClient _client;
        private readonly ITokenService _tokenService;

        public MySocialMediaController(IHttpClientFactory clientFactory, ITokenService tokenService)
        {
            _client = clientFactory.CreateClient("EduClient");
            _tokenService = tokenService;
        }
        public async Task<IActionResult> Index()
            {
                var userId = _tokenService.GetUserId;
                var values = await _client.GetFromJsonAsync<List<ResultTeacherSocialDto>>("teacherSocials/byTeacherId/" + userId);
                return View(values);
            }

            public async Task<IActionResult> DeleteTeacherSocial(int id)
            {
                await _client.DeleteAsync("teacherSocials/" + id);
                return RedirectToAction("Index");
            }

            [HttpGet]
            public IActionResult CreateTeacherSocial()
            {
                return View();
            }

            [HttpPost]
            public async Task<IActionResult> CreateTeacherSocial(CreateTeacherSocialDto createTeacherSocialDto)
            {
                var userId = _tokenService.GetUserId;
                createTeacherSocialDto.TeacherId = userId;
                await _client.PostAsJsonAsync("teacherSocials", createTeacherSocialDto);
                return RedirectToAction(nameof(Index));
            }

            [HttpGet]
            public async Task<IActionResult> UpdateTeacherSocial(int id)
            {

                var value = await _client.GetFromJsonAsync<UpdateTeacherSocialDto>($"teacherSocials/{id}");
                return View(value);
            }

            [HttpPost]
            public async Task<IActionResult> UpdateTeacherSocial(UpdateTeacherSocialDto updateTeacherSocialDto)
            {
            
            await _client.PutAsJsonAsync("teacherSocials", updateTeacherSocialDto);
                return RedirectToAction(nameof(Index));
            }
        }
    }

OnlineEdu.WebUI/Areas/Teacher/Views/MySocialMedia/CreateTeacherSocial.cshtml
@model CreateTeacherSocialDto
@{
    ViewData["Title"] = "Yeni Sosyal Medya Hesabı Oluştur";
    Layout = "~/Areas/Teacher/Views/TeacherLayout/Index.cshtml";
}

<form method="post">

    <label>Sosyal Medya Adı</label>
    <input type="text" asp-for="SocialMediaName" class="form-control" />
    <br />
    <label>Icon</label>
    <input type="text" asp-for="Icon" class="form-control" />
    <br />
    <label>Sosyal Medya Url</label>
    <input type="text" asp-for="Url" class="form-control" />
    <br />  
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>

</form>

OnlineEdu.WebUI/Areas/Teacher/Views/MySocialMedia/Index.cshtml
@model List<ResultTeacherSocialDto>
@{
    ViewData["Title"] = "Sosyal Medyalarım";
    Layout = "~/Areas/Teacher/Views/TeacherLayout/Index.cshtml";
}

@{
    int count = 0;
}

<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Sosyal Medya</th>
        

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td><a href="@item.Url" target="_blank" > <i class="@item.Icon"></i>@item.SocialMediaName</a> </td>
           


            <td>
                <button onclick="deleteMySocial(@item.TeacherSocialId)" class="btn btn-outline-danger">Sil</button>
                <a asp-action="UpdateTeacherSocial" asp-controller="MySocialMedia" asp-area="Teacher" asp-route-id="@item.TeacherSocialId" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
    }
</table>

<br />

<a asp-action="CreateTeacherSocial" asp-controller="MySocialMedia" asp-area="Teacher" class="btn btn-outline-primary">Yeni Sosyal Medya Ekle</a>

<script>

        function deleteMySocial(id) {



                    Swal.fire({
      title: "Silmek istediğinize emin misiniz?",
      text: "Bu işlemi geri alamazsınız!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "Evet, Sil!",
      cancelButtonText: "İptal"
    }).then((result) => {
      if (result.isConfirmed) {

          window.location.href = "/Teacher/MySocialMedia/DeleteTeacherSocial/" + id;

      }
    });

        }

</script>

OnlineEdu.WebUI/Areas/Teacher/Views/MySocialMedia/UpdateTeacherSocial.cshtml
@model UpdateTeacherSocialDto
@{
    ViewData["Title"] = "Sosyal Medya Hesabını Güncelle";
    Layout = "~/Areas/Teacher/Views/TeacherLayout/Index.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="TeacherSocialId"  />
    <label>Sosyal Medya Adı</label>
    <input type="text" asp-for="SocialMediaName" class="form-control" />
    <br />
    <label>Icon</label>
    <input type="text" asp-for="Icon" class="form-control" />
    <br />
    <label>Sosyal Medya Url</label>
    <input type="text" asp-for="Url" class="form-control" />
    <br />
    <br />
    <button class="btn btn-outline-primary">Güncelle</button>

</form>