OnlineEdu.WebUI/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.RoleDtos;


namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    

    public class RoleController : Controller
    {
        private readonly HttpClient _client;

        public RoleController(IHttpClientFactory clientFactory)
        {
            _client = clientFactory.CreateClient("EduClient");
        }
        public async Task<IActionResult> Index()
        {
            var values = await _client.GetFromJsonAsync<List<ResultRoleDto>>("roles");
            return View(values);
        }

        public IActionResult CreateRole()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleDto createRoleDto)
        {
            await _client.PostAsJsonAsync("roles",createRoleDto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteRole(int id)
        {
            await _client.DeleteAsync("roles/" + id);
            return RedirectToAction("Index");
        }
    }
}

OnlineEdu.WebUI/Areas/Admin/Views/Role/CreateRole.cshtml
@model CreateRoleDto
@{
    ViewData["Title"] = "Yeni Rol Oluşturma Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">

    <label>Rol Adı</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>

</form>

OnlineEdu.WebUI/Areas/Admin/Views/Role/Index.cshtml
@model List<ResultRoleDto>

@{
    ViewData["Title"] = "Rol Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    int count = 0;
}

<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Rol Adı</th>
        <th></th>

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Name</td>

            <td>
                <button onclick="deleteRole(@item.Id)" class="btn btn-outline-danger">Sil</button>
                
            </td>
        </tr>
    }
</table>

<br />

<a asp-action="CreateRole" asp-controller="Role" asp-area="Admin" class="btn btn-outline-primary">Yeni Rol Ekle</a>

<script>

        function deleteRole(id) {



                    Swal.fire({
      title: "Silmek istediğinize emin misiniz?",
      text: "Bu işlemi geri alamazsınız!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "Evet, Sil!",
      cancelButtonText: "İptal"
    }).then((result) => {
      if (result.isConfirmed) {

          window.location.href = "/Admin/Role/DeleteRole/" + id;

      }
    });

        }

</script>