OnlineEdu.WebUI/Areas/Admin/Controllers/SocialMediaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.SocialMediaDtos;
using OnlineEdu.WebUI.Helpers;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    
    public class SocialMediaController : Controller
    {
        private readonly HttpClient _client;

        public SocialMediaController(IHttpClientFactory clientFactory)
        {
            _client = clientFactory.CreateClient("EduClient");
        }
        public async Task<IActionResult> Index()
        {
            var values = await _client.GetFromJsonAsync<List<ResultSocialMediaDto>>("SocialMedias");
            return View(values);
        }

        public async Task<IActionResult> DeleteSocialMedia(int id)
        {
            await _client.DeleteAsync("SocialMedias/" + id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public  IActionResult CreateSocialMedia()
        {           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSocialMedia(CreateSocialMediaDto createSocialMediaDto)
        {
            await _client.PostAsJsonAsync("SocialMedias", createSocialMediaDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateSocialMedia(int id)
        {
           
            var value = await _client.GetFromJsonAsync<UpdateSocialMediaDto>($"SocialMedias/{id}");
            return View(value);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSocialMedia(UpdateSocialMediaDto updateSocialMediaDto)
        {
            await _client.PutAsJsonAsync("SocialMedias", updateSocialMediaDto);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/CreateSocialMedia.cshtml
@model CreateSocialMediaDto
@{
    ViewData["Title"] = "Yeni Sosyal Medya Oluştur";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">

    <label>Sosyal Medya Adı</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sosyal Medya Url Linki</label>
    <input type="text" asp-for="Url" class="form-control" />
    <br />
    <label>İkon</label>
    <input type="text" asp-for="Icon" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>

</form>

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/Index.cshtml
@model List<ResultSocialMediaDto>
@{
    ViewData["Title"] = "Sosyal Medya Hesapları";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    int count = 0;
}

<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Sosyal Medya</th>
        

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td><i class="@item.Icon fa-2x"></i><a href="@item.Url" target="_blank">  @item.Title</a></td>
            <td>@item.Title</td>
           
            <td>
                <button onclick="deleteSocialMedia(@item.SocialMediaId)" class="btn btn-outline-danger">Sil</button>
                <a asp-action="UpdateSocialMedia" asp-controller="SocialMedia" asp-area="Admin" asp-route-id="@item.SocialMediaId" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
    }
</table>

<br />

<a asp-action="CreateSocialMedia" asp-controller="SocialMedia" asp-area="Admin" class="btn btn-outline-primary">Yeni SocialMedia Ekle</a>

<script>

        function deleteSocialMedia(id) {



                    Swal.fire({
      title: "Silmek istediğinize emin misiniz?",
      text: "Bu işlemi geri alamazsınız!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "Evet, Sil!",
      cancelButtonText: "İptal"
    }).then((result) => {
      if (result.isConfirmed) {

          window.location.href = "/Admin/SocialMedia/DeleteSocialMedia/" + id;

      }
    });

        }

</script>

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/UpdateSocialMedia.cshtml
@model UpdateSocialMediaDto
@{
    ViewData["Title"] = "Sosyal Medya Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
    <input type="hidden" asp-for="SocialMediaId" />
    <label>Sosyal Medya Adı</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sosyal Medya Url Linki</label>
    <input type="text" asp-for="Url" class="form-control" />
    <br />
    <label>İkon</label>
    <input type="text" asp-for="Icon" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>

</form>