OnlineEdu.WebUI/Areas/Admin/Controllers/RoleAssignController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.UserDtos;
using OnlineEdu.WebUI.Services.UserServices;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    
    public class RoleAssignController : Controller
    {

        private readonly HttpClient _client;
        private readonly IUserService _userService;

        public RoleAssignController(IHttpClientFactory clientFactory, IUserService userService)
        {
            _client = clientFactory.CreateClient("EduClient");
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _userService.GetAllUserAsync();
            
           
            return View(values);
        }

        [HttpGet]
        public async Task<IActionResult> AssignRole(int id)
        {
            var values = await _userService.GetUserForRoleAssign(id);
            return View(values);
        }

        [HttpPost]

        public async Task<IActionResult> AssignRole(List<AssignRoleDto>assignRoleList)
        {
            var result = await _client.PostAsJsonAsync("roleAssigns", assignRoleList);
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
                
            }
            return View(assignRoleList);
        }

    }
}

OnlineEdu.WebUI/Areas/Admin/Views/RoleAssign/AssignRole.cshtml
@using OnlineEdu.WebUI.DTOs.UserDtos

@model List<AssignRoleDto>
@{
    ViewData["Title"] = "Rol Atama Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">

    @for (int i=0;i<Model.Count;i++)
    {
        <div class="form-check">
            <input type="hidden" asp-for="@Model[i].UserId" />

            <input type="hidden" asp-for="@Model[i].RoleId" />
            <input type="hidden" asp-for="@Model[i].RoleName" />
            <input type="checkbox" asp-for="@Model[i].RoleExist" class="form-check-input" />
            <label class="form-check-label" for="@Model[i].RoleExist">@Model[i].RoleName</label>
        </div>
    }

    <button class="btn btn-outline-primary">Rolleri Ata</button>

</form>

OnlineEdu.WebUI/Areas/Admin/Views/RoleAssign/Index.cshtml
@model List<UserViewModel>
@{
    ViewData["Title"] = "Kullanıcı Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    int count = 0;
}

<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Ad Soyad</th>
        <th>Kullanıcı Adı</th>
        <th>Rolleri</th>

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.NameSurname</td>
            <td>@item.UserName</td>
            <td>
                @foreach(var role in item.Roles)
                {
                    <span class="badge bg-dark text-white">@role</span>
                }
            </td>

            <td>
                
                <a asp-action="AssignRole" asp-controller="RoleAssign" asp-area="Admin" asp-route-id="@item.Id" class="btn btn-outline-info">Rol Ata</a>
            </td>
        </tr>
    }
</table>

<br />